Pandas
marlierecharlie/brief_13_la_data_dream_team pull request #12
Opened 2022-12-06 08:22 UTC by LakhbirSin

Valide for William

2022-12-06 15:31 UTC, LakhbirSin commented
Nettoyage de donnée jusqu'au cellule 17

2022-12-07 13:55 UTC, ValBaron10 requested changes
Pourquoi des fichiers Untitled sont-ils commités ? Ça n'a pas de sens... On ne commit que ce qui sert, pas tous ses brouillons qui au final ne servent pas. Là j'ai un gros problème pour savoir quels sont les fichiers que je dois lire et ceux que je ne dois pas lire... Il faut m'expliquer !

Les csv ont été ajoutés au repo alors qu'il ne faut pas ! Si vous les déplacez et que vous ne les mettez pas dans un .gitignore, à chaque fois que vous faites un `git stage .` ils vont s'ajouter à vos commit. Je ne sais pas si c'est comme ça que vous faites mais c'est une très mauvaise pratique !

Il y a pas mal de bonnes idées dans le fichier App Web Prédiction/MS2_NettoyageEtFeat/Millestone 2 Analyse-Copy1.ipynb, mais pour l'instant je ne vois pas encore bien ce que tu veux en faire. Par contre encore une fois il est en double avec ce fichier là DREAMTEAM/Millestone 2 Analyse.ipynb, je ne comprends pas pourquoi.

Il ne faut pas commit tout sans regarder dans le détail ce que vous ajoutez à votre dépôt. Là c'est un peu le bazar, et donc on s'y perd (notamment moi puisque je n'ai pas codé !). Il faut ranger tout ça plus proprement !

2022-12-07 15:09 UTC, marlierecharlie commented
En effet c'est le bazard car on a avancé sur plusieurs points du planning à la fois, au moment du commit on a eu un conflit sur le notebook jupyter. Heureusement que Lakhbir avait fait une copie. Il du recloner le repository pour pouvoir pusher son travail. On range tout et on fera un commit à Yannick en te taggant aussi quand ce sera mieux organisé.

2022-12-07 15:13 UTC, marlierecharlie commented
Tout compte fait es -tu d'accord pour que je supprime cette pull request pour repartir sur un schéma plus clair?

2022-12-08 09:17 UTC, closed without merging